# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [45]:
#Let's start by importing the library
import torch

A <code>torch.Tensor</code> is a multi-dimensional matrix containing elements of a single data type.

In [66]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
# .size() allows to get the size of the tensor
print(t.size())
# also .shape do the same
print(t.shape)

torch.Size([2, 2, 4])
torch.Size([2, 2, 4])


In [47]:
# Generate a tensor filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)

In [48]:
# Print the tensors
print(t, t_r, t_ones)

tensor([[[4.2764e+07, 1.3267e+31, 2.8183e+20, 7.3997e+20],
         [4.5093e+27, 7.6831e+31, 1.9603e-19, 1.9432e-19]],

        [[4.4845e+30, 2.8085e+17, 2.9390e+29, 2.0705e-19],
         [4.4721e+21, 1.4580e-19, 7.3313e+22, 1.8471e+25]]]) tensor([[[-1.6375, -1.2219,  0.6147,  0.3442],
         [-0.0294, -0.7361, -1.0921,  1.2164]],

        [[ 0.3358, -0.3005, -1.1849,  1.4342],
         [-1.8888,  1.1354, -1.2108, -0.4409]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [49]:
# To resize a tensor do
t.resize_(4,4)
print(t.size())
# be CAREFULL with in-place operations like this one
# since they will permanently change the tensor

torch.Size([4, 4])


In [50]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([4, 4]) torch.Size([2, 2])


In [74]:
# Reshaping tensors
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32) # dtype allows to define the type of the elements of the tensors
print(t.shape)
print(t.reshape([1,12]))
print(t.reshape([1,-1]))    # same as above
print(t.reshape([1,12]).squeeze())           # same as above, but flattened
print(t.reshape([2,6]))
print(t.reshape([3,4]))


torch.Size([3, 4])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


In [51]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])


In [52]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)

tensor([7., 8., 9.])


Working with tensors is exactly like working with vectors and matrices!

In [53]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtraction)
print(w + v)
# Element-wise multiplication (or division)
print(w * v)
# Square all elements in the tensor
w2 = w.pow(2)
# and so on...

tensor([10., 10., 10.])
tensor([21., 16.,  9.])


In [54]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [55]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:,2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:, 2:])
print(m[:, :2])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [56]:
# like with vectors you can
# Sum (or subtraction)
b = torch.randn(2,4)
print(m + b)
# Multiplication (or division)
print(m * b)

tensor([[0.7529, 1.4732, 1.7290, 4.5110],
        [5.4559, 6.6790, 6.8640, 8.8323]])
tensor([[-0.2471, -1.0537, -3.8129,  2.0442],
        [ 2.2797,  4.0738, -0.9522,  6.6585]])


In [57]:
# Transpose a matrix
print(m.t())
# Row-by-column multiplication
m2 = m.t()
m3 = torch.matmul(m,m2)
print(m.size())
print(m2.size())
print(m3.size())
print(m3) 

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])
torch.Size([2, 4])
torch.Size([4, 2])
torch.Size([2, 2])
tensor([[ 30.,  70.],
        [ 70., 174.]])


In [58]:
# Flatten a tensor maintaining the same batch size (the first element of the Tensor)
m_4_dim = torch.randn(4,8,2,2)
print(m_4_dim.view(m_4_dim.size(0), -1).size()) 
# Rearrange dimensions
print(m_4_dim.view(m_4_dim.size(0), 16, 2).size()) 

torch.Size([4, 32])
torch.Size([4, 16, 2])


Moving tensors to GPU

In [59]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(m_d.device)

cuda:0


Moving tensors to Numpy

In [60]:
# Converts tensor to numpy array
m_np = m.numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [61]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])

# Concatenate on axis 0
print(torch.cat((a, b), 0))
# Concatenate on axis 1
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [109]:
# Adding and removing dimensions from Tensor
r_t = torch.randn(3,64,64)
# add a dimension
r_t = r_t.unsqueeze(0) # argument is WHERE we want the dimension to be added
print(r_t.size())
# remove a dimension
r_t = r_t.squeeze(0) # argument is WHERE we want the dimension to be removed
print(r_t.size())

torch.Size([1, 3, 64, 64])
torch.Size([3, 64, 64])


In [95]:
# Ex1: Split a 3 dimentional tensors of dimension 4x64x128 
# into 2 tensors of size 4x32x128
# and then concatenate them toghether to get the original size back

torch.Size([4, 64, 128])
torch.Size([4, 32, 128])
torch.Size([4, 64, 128])


In [ ]:
a = torch.randn(4,64,128)
print(a.shape)
b = torch.chunk(a,2,1)
print(b[0].shape)
c = torch.cat((b[0],b[1]),1)
print(c.shape)

In [19]:
# Ex2: You have two matrices of dimension: 4x256x4 and 4x16x64 
# concatenate them toghether to form a single matrix
# of dimension 4x64x32

In [131]:
a = torch.randn(4,256,4)
a = a.view(a.size(0),-1)
print(a.shape)
a2 = torch.chunk(a,16,1)
print(a2[0].shape)
c = torch.stack(a2,2)
print(c.shape)
b = torch.randn(4,16,64)
b = b.view(a.size(0),-1)
print(b.shape)
b2 = torch.chunk(b,16,1) # ciao
print(b2[0].shape)
d = torch.stack(b2,2)
print(d.shape)
e = torch.cat((c,d),2)
print(e.shape)

torch.Size([4, 1024])
torch.Size([4, 64])
torch.Size([4, 64, 16])
torch.Size([4, 1024])
torch.Size([4, 64])
torch.Size([4, 64, 16])
torch.Size([4, 64, 32])
tensor([[ 0.7320,  0.2307,  1.0664,  ...,  0.1528,  0.6943,  1.1013],
        [-0.7276, -0.2944,  0.2911,  ...,  0.9749,  0.5329, -1.0997],
        [ 1.3043,  0.1452, -0.0641,  ...,  1.5099, -0.2420,  0.4071],
        [-0.8918, -0.4085, -1.8522,  ...,  0.2550,  1.1756,  0.2924]])
tensor([[ 0.2089,  0.1434, -0.3333,  ..., -0.2215,  0.3412, -1.1354],
        [ 1.0955,  1.0964,  1.1218,  ...,  0.0752, -1.7886, -0.0832],
        [ 0.3953, -0.4901,  0.3883,  ...,  1.4568,  1.2309, -1.1172],
        [-0.4694, -0.7518,  0.5342,  ...,  1.8350,  1.4087,  0.6191]])
tensor([[[ 0.7320,  0.8817, -1.7894,  ..., -0.9969,  1.3382,  1.6922],
         [ 0.2307,  1.1577, -1.3423,  ..., -0.7225, -0.3695,  1.3684],
         [ 1.0664,  0.0063,  0.6343,  ...,  0.6400, -0.1451, -0.8369],
         ...,
         [-0.9317,  1.1263, -1.5400,  ..., -1.2459, -0.

In [20]:
# Ex3: You have 4 matrixes representing 4 RGB images of dimension 3x128x128.
# Create a grid of dimension 3x256x256