# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [2]:
#Let's start by importing the library
import torch

A <code>torch.Tensor</code> is a multi-dimensional matrix containing elements of a single data type.

In [3]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
# .size() allows to get the size of the tensor
print(t.size())
# also .shape do the same
print(t.shape)

torch.Size([2, 2, 4])
torch.Size([2, 2, 4])


In [4]:
# Generate a tensor filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)

In [5]:
# Print the tensors
print(t, t_r, t_ones)

tensor([[[4.4082e-39, 4.2246e-39, 1.0286e-38, 1.0653e-38],
         [1.0194e-38, 8.4490e-39, 1.0469e-38, 9.3674e-39]],

        [[9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39],
         [9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0653e-38]]]) tensor([[[-0.5167,  1.0820, -0.6305,  0.5838],
         [ 1.2005, -1.5526, -1.2822,  0.3110]],

        [[-0.2026,  0.4504, -0.3075,  0.3934],
         [-0.5660,  0.2005,  0.4667,  0.6104]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [6]:
# To resize a tensor do
t.resize_(4,4)
print(t.size())
# be CAREFULL with in-place operations like this one
# since they will permanently change the tensor

torch.Size([4, 4])


In [7]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([4, 4]) torch.Size([2, 2])


In [8]:
# Reshaping tensors
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32) # dtype allows to define the type of the elements of the tensors
print(t.shape)
print(t.reshape([1,12]))
print(t.reshape([1,-1]))    # same as above
print(t.reshape([1,12]).squeeze())           # same as above, but flattened
print(t.reshape([2,6]))
print(t.reshape([3,4]))


torch.Size([3, 4])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


In [9]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])


In [10]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)

tensor([7., 8., 9.])


Working with tensors is exactly like working with vectors and matrices!

In [11]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtraction)
print(w + v)
# Element-wise multiplication (or division)
print(w * v)
# Square all elements in the tensor
w2 = w.pow(2)
# and so on...

tensor([10., 10., 10.])
tensor([21., 16.,  9.])


In [12]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [13]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:,2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:, 2:])
print(m[:, :2])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [14]:
# like with vectors you can
# Sum (or subtraction)
b = torch.randn(2,4)
print(m + b)
# Multiplication (or division)
print(m * b)

tensor([[0.6055, 1.9343, 5.0750, 2.8201],
        [5.3309, 5.5697, 5.1479, 7.5285]])
tensor([[ -0.3945,  -0.1315,   6.2249,  -4.7195],
        [  1.6544,  -2.5817, -12.9648,  -3.7717]])


In [15]:
# Transpose a matrix
print(m.t())
# Row-by-column multiplication
m2 = m.t()
m3 = torch.matmul(m,m2)
print(m.size())
print(m2.size())
print(m3.size())
print(m3) 

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])
torch.Size([2, 4])
torch.Size([4, 2])
torch.Size([2, 2])
tensor([[ 30.,  70.],
        [ 70., 174.]])


In [16]:
# Flatten a tensor maintaining the same batch size (the first element of the Tensor)
m_4_dim = torch.randn(4,8,2,2)
print(m_4_dim.view(m_4_dim.size(0), -1).size()) 
# Rearrange dimensions
print(m_4_dim.view(m_4_dim.size(0), 16, 2).size()) 

torch.Size([4, 32])
torch.Size([4, 16, 2])


Moving tensors to GPU

In [17]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(m_d.device)

cuda:0


Moving tensors to Numpy

In [18]:
# Converts tensor to numpy array
m_np = m.numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [19]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])

# Concatenate on axis 0
print(torch.cat((a, b), 0))
# Concatenate on axis 1
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [20]:
# Adding and removing dimensions from Tensor
r_t = torch.randn(3,64,64)
# add a dimension
r_t = r_t.unsqueeze(0) # argument is WHERE we want the dimension to be added
print(r_t.size())
# remove a dimension
r_t = r_t.squeeze(0) # argument is WHERE we want the dimension to be removed
print(r_t.size())

torch.Size([1, 3, 64, 64])
torch.Size([3, 64, 64])


In [21]:
# Ex1: Split a 3 dimentional tensors of dimension 4x64x128 
# into 2 tensors of size 4x32x128
# and then concatenate them toghether to get the original size back

In [28]:
a = torch.randn(4,64,128)
print(a.shape)
a_1 = a[:,:32,:]
print(a_1.shape)
a_2 = a[:,32:,:]
print(a_2.shape) 
b = torch.cat((a_1,a_2),1)
print(b.shape)

print('--------')
a = torch.randn(4,64,128)
print(a.shape)
b = torch.chunk(a,2,1)
print(b[0].shape)
c = torch.cat((b[0],b[1]),1)
print(c.shape) 



torch.Size([4, 64, 128])
torch.Size([4, 32, 128])
torch.Size([4, 32, 128])
torch.Size([4, 64, 128])
--------
torch.Size([4, 64, 128])
torch.Size([4, 32, 128])
torch.Size([4, 64, 128])


In [23]:
# Ex2: You have two matrices of dimension: 4x256x4 and 4x16x64 
# concatenate them toghether to form a single matrix
# of dimension 4x64x32

In [24]:
a = torch.randn(4,256,4)
a = a.view(a.size(0),16, 64)
print(a.shape)
b = torch.randn(4,16,64)
c = torch.cat((a,b), dim=1)
print(c.size())
c = c.view(c.size(0), 64, 32)
print(c.size())

torch.Size([4, 16, 64])
torch.Size([4, 32, 64])
torch.Size([4, 64, 32])


In [ ]:
# Ex3: You have 4 matrixes representing 4 RGB images of dimension 3x128x128.
# Create a grid of dimension 3x256x256

In [25]:
a = torch.randint(0, 255, (3,128,128))
b = torch.randint(0, 255, (3,128,128))
c = torch.randint(0, 255, (3,128,128))
d = torch.randint(0, 255, (3,128,128))
ab = torch.cat((a,b), dim = 1)
cd = torch.cat((c,d), dim = 1)
print(ab.size(), cd.size())
abcd = torch.cat((ab, cd), dim = 2)
print(abcd.size())

torch.Size([3, 256, 128]) torch.Size([3, 256, 128])
torch.Size([3, 256, 256])
